version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    container_name: backend_api
    ports:
      - "8765:8765"
    environment:
      - POSTGRES_DB=mvp_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres_db
      - MONGO_HOST=mongo_db
      - MONGO_PORT=27017
    depends_on:
      - postgres_db
      - mongo_db
    volumes:
      - ./backend/app:/app/app  # For live code reload if needed (optional)
    networks:
      - backend_network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.frontend
  #   container_name: frontend_app
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - backend_network

  mongo_db:
    image: mongo:6.0
    container_name: mongo_db
    restart: unless-stopped
    volumes:
      - /media/linux-pc/DB/mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend_network

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mvp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - /media/linux-pc/DB/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
